const banks = [
  "bank tabungan negara",
  "bank permata",
  "bank bukopin",
  "bank ocbc nisp",
  "bank artha graha",
  "bank maybank",
  "bank bpd",
  "bank jabar banten",
  "bank rakyat indonesia",
  "bank rakyat indonesia (syariah)",
  "bank mandiri",
  "bank mega",
  "bank central asia",
  "bank cimb niaga",
  "bank negara indonesia",
  "bank common wealth",
  "bank dki",
  "bank mandiri syariah",
  "bank victoria",
  "BPD Aceh",
  "BPD Aceh UUS",
  "Bank Agris",
  "Bank Agroniaga",
  "Bank Andara",
  "Anglomas International Bank",
  "Bank Antar Daerah",
  "Bank ANZ Indonesia",
  "Bank Arta Niaga Kencana",
  "Bank Artha Graha International",
  "Bank Artos Indonesia",
  "BPD Bali",
  "Bank of America Merill-Lynch",
  "Bangkok Bank",
  "Bank Central Asia (BCA)",
  "Bank Central Asia (BCA) Syariah",
  "BPD Bengkulu",
  "Bank Maybank",
  "Bank Bisnis Internasional",
  "Bank BJB",
  "Bank BJB Syariah",
  "Bank Negara Indonesia (BNI)",
  "Bank BNI Syariah",
  "Bank BNP Paribas",
  "Bank of China (BOC)",
  "Bank Rakyat Indonesia (BRI)",
  "Bank Syariah BRI",
  "Bank Tabungan Negara (BTN)",
  "Bank Tabungan Negara (BTN) UUS",
  "Bank Bukopin",
  "Bank Syariah Bukopin",
  "Bank Bumi Arta",
  "Bank Capital Indonesia",
  "Centratama Nasional Bank",
  "Bank Chinatrust Indonesia",
  "Bank CIMB Niaga",
  "Bank CIMB Niaga UUS",
  "Citibank",
  "Bank Commonwealth",
  "BPD Daerah Istimewa Yogyakarta (DIY)",
  "BPD Daerah Istimewa Yogyakarta (DIY) UUS",
  "Bank Danamon",
  "Bank Danamon UUS",
  "Bank DBS Indonesia",
  "Deutsche Bank",
  "Bank Dinar Indonesia",
  "Bank DKI",
  "Bank DKI UUS",
  "Bank Ekonomi Raharja",
  "Bank Ekspor Indonesia",
  "Bank Fama International",
  "Bank Ganesha",
  "Bank Hana",
  "Bank Harda Internasional",
  "Bank Himpunan Saudara 1906",
  "Hongkong and Shanghai Bank Corporation (HSBC)",
  "Hongkong and Shanghai Bank Corporation (HSBC) UUS",
  "Bank ICBC Indonesia",
  "Bank Ina Perdania",
  "Bank Index Selindo",
  "Bank of India Indonesia",
  "BPD Jambi",
  "BPD Jambi UUS",
  "Bank Jasa Jakarta",
  "BPD Jawa Tengah",
  "BPD Jawa Tengah UUS",
  "BPD Jawa Timur",
  "BPD Jawa Timur UUS",
  "JP Morgan Chase Bank",
  "BPD Kalimantan Barat",
  "BPD Kalimantan Barat UUS",
  "BPD Kalimantan Selatan",
  "BPD Kalimantan Selatan UUS",
  "BPD Kalimantan Tengah",
  "BPD Kalimantan Timur",
  "BPD Kalimantan Timur UUS",
  "Bank Kesejahteraan Ekonomi",
  "BPD Lampung",
  "BPD Maluku",
  "Bank Mandiri",
  "Bank Syariah Mandiri",
  "Bank Maspion Indonesia",
  "Bank Mayapada International",
  "Bank Maybank Syariah Indonesia",
  "Bank Mayora",
  "Bank Mega",
  "Bank Syariah Mega",
  "Bank Mestika Dharma",
  "Bank Metro Express",
  "Bank Mitra Niaga",
  "Bank Sumitomo Mitsui Indonesia",
  "Bank Mizuho Indonesia",
  "Bank MNC Internasional",
  "Bank Muamalat Indonesia",
  "Bank Multi Arta Sentosa",
  "Bank Mutiara",
  "Bank Nationalnobu",
  "BPD Nusa Tenggara Barat",
  "BPD Nusa Tenggara Barat UUS",
  "BPD Nusa Tenggara Timur",
  "Bank Nusantara Parahyangan",
  "Bank OCBC NISP",
  "Bank OCBC NISP UUS",
  "Bank Panin",
  "Bank Panin Syariah",
  "BPD Papua",
  "Bank Permata",
  "Bank Permata UUS",
  "Prima Master Bank",
  "Bank Pundi Indonesia",
  "Bank QNB Kesawan",
  "Bank Rabobank International Indonesia",
  "Royal Bank of Scotland (RBS)",
  "Bank Resona Perdania",
  "BPD Riau Dan Kepri",
  "BPD Riau Dan Kepri UUS",
  "Bank Royal Indonesia",
  "Bank Sahabat Purba Danarta",
  "Bank Sahabat Sampoerna",
  "Bank SBI Indonesia",
  "Bank Sinar Harapan Bali",
  "Sinarmas",
  "Standard Charted Bank",
  "BPD Sulawesi Tengah",
  "BPD Sulawesi Tenggara",
  "BPD Sulselbar",
  "BPD Sulselbar UUS",
  "BPD Sulut",
  "BPD Sumatera Barat",
  "BPD Sumatera Barat UUS",
  "BPD Sumsel Dan Babel",
  "BPD Sumsel Dan Babel UUS",
  "BPD Sumut",
  "BPD Sumut UUS",
  "Bank Tabungan Pensiunan Nasional",
  "Bank Tabungan Pensiunan Nasional UUS",
  "Bank of Tokyo Mitsubishi UFJ",
  "Bank UOB Indonesia",
  "Bank Victoria Internasional",
  "Bank Victoria Syariah",
  "Bank Windu Kentjana Int",
  "Bank Woori Indonesia",
  "Bank Yudha Bhakti",
];

const cekrekening_bankids = {
  "bank tabungan negara": "589ecaa90483ef26fa00000b",
  "bank permata": "589ecaaa0483ef26fa00000d",
  "bank bukopin": "589ecaaa0483ef26fa00000e",
  "bank ocbc nisp": "589ecaaa0483ef26fa00000f",
  "bank artha graha": "589ecaa90483ef26fa00000c",
  "bank maybank": "589ecaaa0483ef26fa000010",
  "bank bpd": "58b2ad730483ef3dce000000",
  "bank jabar banten": "58ba961d0483ef1663000000",
  "bank rakyat indonesia": "589ecaa80483ef26fa000004", // Other: "5913b2aa0483ef15540005ae"
  "bank mandiri": "589ecaa80483ef26fa000005",
  "bank mega": "589ecaa80483ef26fa000006",
  "bank central asia": "589ecaa80483ef26fa000007",
  "bank cimb niaga": "58ba961e0483ef1663000001",
  "bank negara indonesia": "589ecaa90483ef26fa000008",
  "bank dki": "589ecaa90483ef26fa000009",
  "bank mandiri syariah": "589ecaa90483ef26fa00000a",
};

module.exports = {
  banks,
  cekrekening_bankids,
};
