export const banks = [
  "Bank Tabungan Negara",
  "Bank Permata",
  "Bank Bukopin",
  "Bank OCBC NISP",
  "Bank Artha Graha",
  "Bank Maybank",
  "Bank BPD",
  "Bank Lainnya",
  "Bank Jabar Banten",
  "Bank Rakyat Indonesia",
  "Bank Rakyat Indonesia (Syariah)",
  "Bank Mandiri",
  "Bank Mega",
  "Bank Central Asia",
  "Bank Rakyat Indonesia",
  "Bank CIMB Niaga",
  "Bank Negara Indonesia",
  "Bank Common Wealth",
  "Bank DKI",
  "Bank Mandiri Syariah",
  "Bank Victoria",
  "Unknown"
];
